development:
  adapter: postgresql
  encoding: unicode
  database: photodeco_development
  pool: 5
  username: photodeco
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: photodeco_test
  pool: 5
  username: photodeco
  password:
